from django.urls import path

from . import views

urlpatterns = [path('', views.home, name='home'),
               path('test', views.testpage, name="test"),
               path('login', views.loginp, name='login'),
               path('form', views.checklogin, name='check'),
            #    path('success/<int:manager_id>/', views.success, name='success'),
               path('dashboardAdmin', views.dashboardAdmin, name='dashboardAdmin'),
               path('gestionClient', views.gestionClient, name="gestionClient"),
               path('gererManagers', views.gestionManagers, name="gestionManagers"),
               path('deleteClient/<int:id>/', views.delete_client, name='delete_client'),
               path('remove/<int:id>/', views.delete_manager, name='delete_manager'),
               path('add_client', views.add_client, name="add_client"),
               path('add_manager', views.add_manager, name="add_manager"),
               path('show_client/<int:id>/', views.show_client, name='show_client'),
               path('show_manager/<int:id>/', views.show_manager, name='show_manager'),
               path('update/<int:id>/', views.update_client, name='update_client'),
               path('updateManger/<int:manager_id>/', views.update_manager, name='update_manager'),
               path('cars', views.carsp, name="cars"),
               path('addcar', views.addcar, name="addcar"),
               path('caradded', views.caradded, name="caradded"),
               path('delete/<int:id>', views.deletecar, name="deletecar"),
               path('car/<int:id>', views.cardetails, name="details"),
               path('carnotfound',views.carnotfound,name='carnotfound'), 
               path('addres/<int:carid>',views.addres,name='add reservation'),
               path('res_conf',views.res_conf, name='confirm reservation'),
               path('reservations',views.reserv,name='liste de reservations'),
               path('carupdate',views.carupdate,name='update car'),
               path('res_a/<int:idres>',views.accepter_res),
               path('res_r/<int:idres>',views.refuser_res),
               path('gestionReservation', views.gestionReservation, name="gestionReservation"),
               ]
